--- #YAML:1.0
name:                Net-LDAP-Batch
version:             0.02
abstract:            perform a batch of LDAP actions
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    Data::Dump:                    0
    Net::LDAP:                     0
    Net::LDAP::Server::Test:       0.04
    Scalar::Util:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
